/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_panzq_simpleandroid_15_2_CalculateUtil */

#ifndef _Included_com_example_panzq_simpleandroid_15_2_CalculateUtil
#define _Included_com_example_panzq_simpleandroid_15_2_CalculateUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_panzq_simpleandroid_15_2_CalculateUtil
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_panzq_simpleandroid_115_12_CalculateUtil_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_example_panzq_simpleandroid_15_2_CalculateUtil
 * Method:    sub
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_panzq_simpleandroid_115_12_CalculateUtil_sub
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_example_panzq_simpleandroid_15_2_CalculateUtil
 * Method:    mul
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_panzq_simpleandroid_115_12_CalculateUtil_mul
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_example_panzq_simpleandroid_15_2_CalculateUtil
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_panzq_simpleandroid_115_12_CalculateUtil_div
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
